<!-- BEGIN LOGO -->
<div class="logo">
    <a class='btn btn-large btn-primary' href='<?php echo $this->url("home"); ?>'>Retour</a>
</div>
<!-- END LOGO -->
<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
<div class="menu-toggler sidebar-toggler">
</div>
<!-- END SIDEBAR TOGGLER BUTTON -->
<!-- BEGIN LOGIN -->
<div class="content">
    <!-- BEGIN LOGIN FORM -->
    <form class="login-form" action="<?php echo $this->url("home_login"); ?>" method="post">
        <h3 class="form-title">Projet 7 - Authentification</h3>
        <div class="alert alert-danger display-hide">
            <button class="close" data-close="alert"></button>
            <span> Entrer un email et un password. </span>
        </div>
        <?php if (isset($this->error)): ?>
            <div class="alert alert-danger">
                <strong>Attention!</strong> <?= $this->error ?>
            </div>
        <?php endif; ?>

        <?php
        if (count($this->form_login->getMessages("email")) > 0) {
            $emailW = "has-warning";
        } else {
            $emailW = "";
        }
        ?>
        <div class="form-group <?= $emailW ?>">
            <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
            <label class="control-label visible-ie8 visible-ie9">Email</label>
            <div class="input-icon <?= $emailW ?>">
                <i class="fa fa-envelope"></i>
                <input class="form-control placeholder-no-fix" type="email" autocomplete="off" placeholder="Email" name="email"
                       <?php if (isset($this->form_login)): ?> value="<?php echo $this->form_login->get("email")->getValue() ?>"  <?php endif; ?>
                       />
            </div>
        </div>
        <?php
        if (count($this->form_login->getMessages("password")) > 0) {
            $passwordW = "has-warning";
        } else {
            $passwordW = "";
        }
        ?>
        <div class="form-group <?= $passwordW ?>">
            <label class="control-label visible-ie8 visible-ie9">Password</label>
            <div class="input-icon <?= $passwordW ?>">
                <i class="fa fa-lock"></i>
                <input class="form-control placeholder-no-fix" type="password" autocomplete="off" placeholder="Password" name="password"/>
            </div>
            <?php foreach ($this->form_login->getMessages("password") as $err): ?>
                <span class="help-block">
                    <?= $err ?>
                </span>
            <?php endforeach; ?>
        </div>

        <input type="hidden" name="<?php echo $this->form_login->get("token_csrf")->getName(); ?>" value="<?php echo $this->form_login->get("token_csrf")->getValue(); ?>" />
        <div class="form-actions">
            <label class="checkbox">
                <!--<input type="checkbox" name="remember" value="1"/> Remember me </label>-->
                <button type="submit" class="btn green pull-right">
                    Authentification <i class="m-icon-swapright m-icon-white"></i>
                </button>
        </div>
        <!--        
        <div class="login-options">
                    <h4>Or login with</h4>
                    <ul class="social-icons">
                        <li>
                            <a class="facebook" data-original-title="facebook" href="#">
                            </a>
                        </li>
                        <li>
                            <a class="twitter" data-original-title="Twitter" href="#">
                            </a>
                        </li>
                        <li>
                            <a class="googleplus" data-original-title="Goole Plus" href="#">
                            </a>
                        </li>
                        <li>
                            <a class="linkedin" data-original-title="Linkedin" href="#">
                            </a>
                        </li>
                    </ul>
                </div>
        -->
        <div class="forget-password">
            <h4>Password oublié ?</h4>
            <p>
                Pas q'inquiétude, cliquez <a href="javascript:;" id="forget-password">
                    ici </a>
                pour reset votre password.
            </p>
        </div>
        <div class="create-account">
            <p>
                Vous n'avez pas encore de compte ?&nbsp; <a class='btn btn-primary' href="javascript:;" id="register-btn">
                    Créer un compte </a>
            </p>
        </div>
    </form>
    <!-- END LOGIN FORM -->
    <!-- BEGIN FORGOT PASSWORD FORM -->
    <form class="forget-form" method="post">
        <h3>Forget Password ?</h3>
        <p>
            Enter your e-mail address below to reset your password.
        </p>
        <div class="form-group">
            <div class="input-icon">
                <i class="fa fa-envelope"></i>
                <input class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="Email" name="email"/>
            </div>
        </div>
        <div class="form-actions">
            <button type="button" id="back-btn" class="btn">
                <i class="m-icon-swapleft"></i> Back </button>
            <button type="submit" class="btn green pull-right">
                Submit <i class="m-icon-swapright m-icon-white"></i>
            </button>
        </div>
    </form>
    <!-- END FORGOT PASSWORD FORM -->
    <!-- BEGIN REGISTRATION FORM -->
    <form class="register-form" method="post" action="<?php echo $this->url("home_inscription") ?>">
        <input type="hidden" name="<?php echo $this->form_inscription->get("token_csrf")->getName(); ?>" value="<?php echo $this->form_inscription->get("token_csrf")->getValue(); ?>" />
        <h3>Sign Up</h3>
        <p>
            Enter your personal details below:
        </p>
        <div class="form-group">
            <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
            <label class="control-label visible-ie8 visible-ie9">Email</label>
            <div class="input-icon">
                <i class="fa fa-envelope"></i>
                <input class="form-control placeholder-no-fix" type="text" placeholder="Email" name="<?php echo $this->form_inscription->get("email")->getName(); ?>"/>
            </div>
        </div>
        <div class="form-group">
            <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
            <label class="control-label visible-ie8 visible-ie9">Pseudo</label>
            <div class="input-icon">
                <i class="fa fa-font"></i>
                <input class="form-control placeholder-no-fix" type="text" placeholder="Pseudo" name="<?php echo $this->form_inscription->get("username")->getName(); ?>"/>
            </div>
        </div>
        <div class="form-group">
            <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
            <label class="control-label visible-ie8 visible-ie9">Nom</label>
            <div class="input-icon">
                <i class="fa fa-font"></i>
                <input class="form-control placeholder-no-fix" type="text" placeholder="Nom" name="<?php echo $this->form_inscription->get("nom")->getName(); ?>"/>
            </div>
        </div>
        <div class="form-group">
            <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
            <label class="control-label visible-ie8 visible-ie9">Prénom</label>
            <div class="input-icon">
                <i class="fa fa-font"></i>
                <input class="form-control placeholder-no-fix" type="text" placeholder="Prénom" name="<?php echo $this->form_inscription->get("prenom")->getName(); ?>"/>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">Password</label>
            <div class="input-icon">
                <i class="fa fa-lock"></i>
                <input class="form-control placeholder-no-fix" type="password" autocomplete="off" id="register_password" placeholder="Password" name="<?php echo $this->form_inscription->get("passwd0")->getName(); ?>"/>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">Re-type Your Password</label>
            <div class="controls">
                <div class="input-icon">
                    <i class="fa fa-check"></i>
                    <input class="form-control placeholder-no-fix" type="password" autocomplete="off" placeholder="Re-type Your Password" name="<?php echo $this->form_inscription->get("passwd1")->getName(); ?>"/>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label>
                <input type="checkbox" name="tnc"/> I agree to the <a href="#">
                    Terms of Service </a>
                and <a href="#">
                    Privacy Policy </a>
            </label>
            <div id="register_tnc_error">
            </div>
        </div>
        <div class="form-actions">
            <button id="register-back-btn" type="button" class="btn">
                <i class="m-icon-swapleft"></i> Back </button>
            <button type="submit" id="register-submit-btn" class="btn green pull-right">
                Sign Up <i class="m-icon-swapright m-icon-white"></i>
            </button>
        </div>
    </form>
    <!-- END REGISTRATION FORM -->
</div>
<!-- END LOGIN -->
<!-- BEGIN COPYRIGHT -->
<div class="copyright">
    2014 &copy; Metronic. Admin Dashboard Template.
</div>
<!-- END COPYRIGHT -->