<!-- Header BEGIN -->
<div class="header header-mobi-ext">
    <div class="container">
        <div class="row">
            <!-- Logo BEGIN -->
            <div class="col-md-2 col-sm-2">
                <a class="scroll site-logo" href="#promo-block"><img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/logo/blue.png" alt="Metronic One Page"></a>
            </div>
            <!-- Logo END -->

            <a href="javascript:void(0);" class="mobi-toggler"><i class="fa fa-bars"></i></a>

            <!-- Navigation BEGIN -->
            <div class="col-md-10 pull-right">
                <ul class="header-navigation">
                    <li class="current"><a href="">Acceuil  </a></li>
                    <li><a href="<?php echo $this->url("home_login") ?>">Login</a></li>
                </ul>
            </div>
            <!-- Navigation END -->
        </div>
    </div>
</div>
<!-- Header END -->

<!-- Promo block BEGIN -->
<div class="promo-block" id="promo-block">
    <div class="tp-banner-container">
        <div class="tp-banner" >
            <ul>
                <li data-transition="fade" data-slotamount="5" data-masterspeed="700" data-delay="9400" class="slider-item-1">
                    <img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/silder/slide1.jpg" alt="" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat">
                    <div class="tp-caption large_text customin customout start"
                         data-x="center"
                         data-hoffset="0"
                         data-y="center"
                         data-voffset="60"
                         data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
                         data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                         data-speed="1000"
                         data-start="500"
                         data-easing="Back.easeInOut"
                         data-endspeed="300">
                        <div class="promo-like"><i class="fa fa-thumbs-up"></i></div>
                        <div class="promo-like-text">
                            <h2>Let's just do it</h2>
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing<br> elit amet sed diam nonummy nibh <a href="javascript:void(0);">dolore</a></p>
                        </div>
                    </div>
                    <div class="tp-caption large_bold_white fade"
                         data-x="center"
                         data-y="center"
                         data-voffset="-110"
                         data-speed="300"
                         data-start="1700"
                         data-easing="Power4.easeOut"
                         data-endspeed="500"
                         data-endeasing="Power1.easeIn"
                         data-captionhidden="off"
                         style="z-index: 6">Parallax <span>One Page</span> Has Arrived
                    </div>
                </li>
                <li data-transition="fadefromright" data-slotamount="5" data-masterspeed="700" data-delay="9400" class="slider-item-2">
                    <img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/silder/Slide2_bg.jpg" alt="slidebg2" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat">
                    <div class="caption lft start"
                         data-y="center"
                         data-voffset="40"
                         data-x="center"
                         data-hoffset="-250"
                         data-speed="600" 
                         data-start="500" 
                         data-easing="easeOutBack"><img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/silder/Slide2_iphone_left.png" alt="">
                    </div>
                    <div class="caption lft start"
                         data-y="center"
                         data-voffset="130"
                         data-x="center"
                         data-hoffset="170"
                         data-speed="600" 
                         data-start="1200" 
                         data-easing="easeOutBack"><img src="<?php echo $this->basePath() ?>/assets/frontend/onepage/img/silder/Slide2_iphone_right.png" alt="">
                    </div>
                    <div class="tp-caption large_bold_white fade"
                         data-x="center"
                         data-y="40"
                         data-speed="300"
                         data-start="1700"
                         data-easing="Power4.easeOut"
                         data-endspeed="500"
                         data-endeasing="Power1.easeIn"
                         data-captionhidden="off"
                         style="z-index: 6">Extremely <span>Responsive</span> Design
                    </div>
                </li>
                <li data-transition="fade" data-slotamount="5" data-masterspeed="700" data-delay="9400" class="slider-item-3">

                    <div class="tp-caption tp-fade fadeout fullscreenvideo"
                         data-x="0"
                         data-y="0"
                         data-speed="1000"
                         data-start="1100"
                         data-easing="Power4.easeOut"
                         data-endspeed="1500"
                         data-endeasing="Power4.easeIn"
                         data-autoplay="true"
                         data-autoplayonlyfirsttime="false"
                         data-nextslideatend="true"
                         data-forceCover="1"
                         data-dottedoverlay="twoxtwo"
                         data-aspectratio="16:9"
                         data-forcerewind="on"
                         style="z-index: 2">

                        <video class="video-js vjs-default-skin" preload="none" width="100%" height="100%">
                            <source src='http://goodwebtheme.com/previewvideo/forest_edit.mp4' type='video/mp4'>
                            <source src='http://goodwebtheme.com/previewvideo/forest_edit.webm' type='video/webm'>
                            <source src='http://goodwebtheme.com/previewvideo/forest_edit.ogv' type='video/ogg'>
                        </video>
                    </div>

                    <div class="tp-caption large_bold_white_25 customin customout tp-resizeme"
                         data-x="center" data-hoffset="0"
                         data-y="170"
                         data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:5;scaleY:5;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                         data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                         data-speed="600"
                         data-start="1400"
                         data-easing="Power4.easeOut"
                         data-endspeed="600"
                         data-endeasing="Power0.easeIn"
                         style="z-index: 3">The clearest way into the Universe<br/>is through a forest wilderness.
                    </div>

                    <div class="tp-caption medium_text_shadow customin customout tp-resizeme"
                         data-x="center" data-hoffset="0"
                         data-y="bottom" data-voffset="-140"
                         data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:5;scaleY:5;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                         data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                         data-speed="600"
                         data-start="1700"
                         data-easing="Power4.easeOut"
                         data-endspeed="600"
                         data-endeasing="Power0.easeIn"
                         style="z-index: 4">John Muir
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- Promo block END -->

<!-- BEGIN PRE-FOOTER -->
<div class="pre-footer" id="contact">
    <div class="container">
        <div class="row">
            <!-- BEGIN BOTTOM ABOUT BLOCK -->
            <div class="col-md-4 col-sm-6 pre-footer-col">
                <h2>About us</h2>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam sit nonummy nibh euismod tincidunt ut laoreet dolore magna aliquarm erat sit volutpat. Nostrud exerci tation ullamcorper suscipit lobortis nisl aliquip  commodo consequat. </p>
                <p>Duis autem vel eum iriure dolor vulputate velit esse molestie at dolore.</p>
            </div>
            <!-- END BOTTOM ABOUT BLOCK -->

            <!-- BEGIN TWITTER BLOCK --> 
            <div class="col-md-4 col-sm-6 pre-footer-col">
                <h2 class="margin-bottom-0">Latest Tweets</h2>
                <a class="twitter-timeline" href="https://twitter.com/twitterapi" data-tweet-limit="2" data-theme="dark" data-link-color="#57C8EB" data-widget-id="455411516829736961" data-chrome="noheader nofooter noscrollbar noborders transparent">Loading tweets by @keenthemes...</a>      
            </div>
            <!-- END TWITTER BLOCK -->

            <div class="col-md-4 col-sm-6 pre-footer-col">
                <!-- BEGIN BOTTOM CONTACTS -->
                <!-- END BOTTOM CONTACTS -->

                <!--                <div class="pre-footer-subscribe-box">
                                    <h2>Newsletter</h2>
                                    <form action="javascript:void(0);">
                                        <div class="input-group">
                                            <input type="text" placeholder="youremail@mail.com" class="form-control">
                                            <span class="input-group-btn">
                                                <button class="btn btn-primary" type="submit">Subscribe</button>
                                            </span>
                                        </div>
                                    </form>
                                </div>-->
            </div>
        </div>
    </div>
</div>
<!-- END PRE-FOOTER -->

<!-- BEGIN FOOTER -->
<div class="footer">
    <div class="container">
        <div class="row">
            <!-- BEGIN COPYRIGHT -->
            <div class="col-md-6 col-sm-6">
                <div class="copyright">2014-2015 © Black Pony Company, Nordi. ALL Rights Reserved.</div>
            </div>
            <!-- END COPYRIGHT -->
            <!-- BEGIN SOCIAL ICONS -->
            <div class="col-md-6 col-sm-6 pull-right">
                <ul class="social-icons">
                    <!--<li><a class="rss" data-original-title="rss" href="javascript:void(0);"></a></li>-->
                    <li><a class="facebook" data-original-title="facebook" href="javascript:void(0);"></a></li>
                    <li><a class="twitter" data-original-title="twitter" href="javascript:void(0);"></a></li>
                    <li><a class="googleplus" data-original-title="googleplus" href="javascript:void(0);"></a></li>
                    <!--<li><a class="linkedin" data-original-title="linkedin" href="javascript:void(0);"></a></li>-->
                    <li><a class="youtube" data-original-title="youtube" href="javascript:void(0);"></a></li>
                    <!--<li><a class="vimeo" data-original-title="vimeo" href="javascript:void(0);"></a></li>-->
                    <!--<li><a class="skype" data-original-title="skype" href="javascript:void(0);"></a></li>-->
                </ul>
            </div>
            <!-- END SOCIAL ICONS -->
        </div>
    </div>
</div>
<!-- END FOOTER -->

<a href="#promo-block" class="go2top scroll"><i class="fa fa-arrow-up"></i></a>
